- defaults:
    link:
      create: true
      relink: true

- clean:
    ~/:
      force: true
    ~/.config:
      recursive: true

- link:
    ~/bin/helper-scripts:
      glob: true
      path: config/helper-scripts/*
    ~/.config/powerline/:
      glob: true
      path: config/powerline/*
    # TMUX config
    ~/.tmux.conf: config/tmux/tmux.conf

- shell:
    # Clone tpm if we don't already have it. The || true is just so we won't fail
    # if it is already installed
    - [git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm || true]

- create:
    - ~/bin
    - ~/bin/helper-scripts
