#!/usr/bin/env bash

set -e
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

INDENTATION="  "
MYNAME=${0##*/}  # Short program name for diagnostic messages.
CONFIG="install.conf.yaml"
DESCRIPTION="description.md"
INSTALL_OPTIONS=$(ls options | grep -vFxf .dots-ignore)
OPTIONS_DIR="options"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

# Update dotbot
cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"


# Print the help menu with descriptions from all available packages
function help(){
  echo "Usage: $MYNAME <Option> [dotbot args (optional)]"
  echo "Options:"
  for file in $INSTALL_OPTIONS;do
    echo "$INDENTATION- $file: $( cat $BASEDIR/$OPTIONS_DIR/$file/$DESCRIPTION)"
  done
  echo "$INDENTATION- help: Show this message and exit"
  exit $1
}


# Create an array of 1's representing an option is available to be installed
declare -A AVAILABLE_TO_INSTALL
for constant in $INSTALL_OPTIONS
do
  AVAILABLE_TO_INSTALL[$constant]=1
done


# Rename the first param to option and install it if it was available
option=$1
if [ ! -z "$option" ]; then
  shift 1
  if [[ ${AVAILABLE_TO_INSTALL[$option]} ]];then
    echo "Install Option: $option was selected."
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}/$OPTIONS_DIR/$option" -c "${BASEDIR}/$OPTIONS_DIR/$option/${CONFIG}" "${@}"
  else
    echo "Install Option: $option was not available."
    help
  fi
else
  help
fi
