#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

function shared() {
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}/shared" -c "${BASEDIR}/shared/${CONFIG}" "${@}"
}

function linux() {
  "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}/linux" -c "${BASEDIR}/linux/${CONFIG}" "${@}"
}

function help(){
  echo "Options for this script include:
    - shared - Install dotfiles relating to my wsl/linux terminal development
    - linux - Install dotfiles relating to my dwm install
    - help - Show this message and exit
"
}

echo You are trying to install/update "$1"
option=$1
shift 1
case $option in
 help)
   help
   ;;
 linux)
   linux $rest
   ;;
 shared)
   shared $rest
   ;;
 *)
   help
   ;;
esac

unset help
unset linux
unset shared
