#!/usr/bin/env bash

set -e
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

INDENTATION="  "
MYNAME=${0##*/}  # Short program name for diagnostic messages.
CONFIG="install.conf.yaml"
DESCRIPTION="description.md"
UNINSTALL_OPTIONS=$(ls | grep -vFxf .dots-ignore)

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

# Print the help menu with descriptions from all available packages
function help(){
  echo "Usage: $MYNAME <Option>"
  echo "Options:"
  for file in $UNINSTALL_OPTIONS;do
    echo "$INDENTATION- $file: $( cat $BASEDIR/$file/$DESCRIPTION)"
  done
  echo "$INDENTATION- help: Show this message and exit"
  exit $1
}


# Create an array of 1's representing an option is available to be uninstalled
declare -A AVAILABLE_TO_UNINSTALL
for constant in $UNINSTALL_OPTIONS
do
  AVAILABLE_TO_UNINSTALL[$constant]=1
done


# Rename the first param to option and uninstall it if it was available
option=$1
if [ ! -z "$option" ]; then
  shift 1
  if [[ ${AVAILABLE_TO_UNINSTALL[$option]} ]];then
    echo "Uninstall Option: $option was selected."
    ${BASEDIR}/scripts/uninstall $BASEDIR/$option/$CONFIG
  else
    echo "Uninstall Option: $option was not available."
    help
  fi
else
  help
fi
