- defaults:
    link:
      create: true
      relink: true

- clean:
    ~/:
      force: true
    ~/.config:
      recursive: true

- link:
    ~/bin/helper-scripts: config/helper-scripts
    ~/bin/os-scripts: config/os-scripts
    # Misc
    ~/.config/bat/:
      glob: true
      path: config/bat/*
    ~/.config/powerline/:
      glob: true
      path: config/powerline/*
    ~/.gitconfig: config/gitconfig
    # NVIM config
    ~/.config/nvim/:
      glob: true
      path: config/neovim/*
    # TMUX config
    ~/.tmux.conf: config/tmux/tmux.conf
    # ZSH config
    ~/.zshenv: config/zsh/zshenv
    ~/.zshrc: config/zsh/zshrc
    ~/.config/zsh/p10k.zsh: config/zsh/p10k.zsh
    ~/.config/zsh/p10k-portable.zsh: config/zsh/p10k-portable.zsh
    # Ranger config
    ~/.config/ranger/:
      glob: true
      path: config/ranger/*

- create:
    - ~/.config/nvim/spell/
    - ~/.config/nvim/undodir/
    - ~/bin

- shell:
    - [git submodule update --init --recursive, Installing submodules]
