- defaults:
    link:
      create: true
      relink: true

# TODO: Check if this deletes other shared config
- clean:
    ~/.config:
      recursive: true

- link:
    # Misc
    ~/.config/sxhkd/sxhkdrc: config/sxhkdrc
