- defaults:
    link:
      create: true
      relink: true

- clean:
    ~/:
      force: true
    ~/.config:
      recursive: true

- link:
    # NVIM config
    ~/.config/nvim/:
      glob: true
      path: config/neovim/*
    ~/.vsnip/:
      glob: true
      path: config/vsnip/*

- create:
    - ~/.config/nvim/spell/
    - ~/.config/nvim/undodir/
