#! /bin/env bash
# Adds `~/bin/*` directories to $PATH
export PATH="$PATH:$(du "$HOME/bin/" | cut -f2 | tr '\n' ':' | sed 's/:*$//')"

# Fix lang
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

# Default programs:
export EDITOR=/usr/bin/nvim
export BROWSER=/usr/bin/chromium # fix "xdg-open fork-bomb"

# QT settings
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_GRAPHICSSYSTEM="opengl"

# ~/ cleanup
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache/"
# export LESSHISTFILE="-" # Commented for use with git diff pager stuff
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
# export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/inputrc"
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export GOPATH="$XDG_DATA_HOME"/go
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/android"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/npm/npmrc"
export NVM_DIR="$XDG_DATA_HOME"/nvm
export _Z_DATA="$XDG_DATA_HOME/z"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export ADOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/antigen"
export ANTIGEN_CHECK_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/zsh/.zshrc"

xsetroot -cursor_name left_ptr &
