#!/usr/bin/env bash

LOCK_COMMAND="i3lock-fancy-dualmonitor"
GREETER="gdm"

case "$1" in
    lock)
        $LOCK_COMMAND
        ;;
    logout)
        if [ $GREETER ];then
          systemctl restart $GREETER
        else
          killall xinit
        fi
        ;;
    suspend)
        systemctl suspend
        ;;
    hibernate)
        systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 [lock|logout|suspend|hibernate|reboot|shutdown]"
        exit 2
esac

exit 0
