- defaults:
    link:
      create: true
      relink: true

- clean:
    ~/:
      force: true
    ~/.config:
      recursive: true

- link:
    # Ranger config
    ~/.config/ranger/:
      glob: true
      path: config/ranger/*
