
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Move the zsh history file
HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/zsh_history"


# Zgen
source "${HOME}/bin/helper-scripts/zgen.zsh"

if ! zgen saved; then
  zgen oh-my-zsh

  zgen oh-my-zsh plugins/z
  zgen oh-my-zsh plugins/git
  zgen oh-my-zsh plugins/docker
  zgen oh-my-zsh plugins/docker-compose
  zgen oh-my-zsh plugins/history-substring-search

  zgen load zsh-users/zsh-syntax-highlighting
  zgen load zsh-users/zsh-completions src
  zgen load romkatv/powerlevel10k powerlevel10k

  zgen save

fi

# Enable Powerlevel10k instant prompt.
[[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]] && \
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
if [[ $DISPLAY || $WSL_ACTIVE ]]; then
  [[ ! -f ~/.config/zsh/p10k.zsh ]] || source ~/.config/zsh/p10k.zsh
else
  . $HOME/bin/helper-scripts/dracula-tty.sh
  [[ ! -f ~/.config/zsh/p10k-portable.zsh ]] || source ~/.config/zsh/p10k-portable.zsh
fi

# Programs and scripts
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -d "$HOME/.fnm" ] && export PATH=/home/nichtj3/.fnm:$PATH
eval "`fnm env`"


# Completion
compdef _tmux tmux-manager
compdef _tmux tmux

# User config
# Enable Vi mode
bindkey -v
export KEYTIMEOUT=1

# Make CTRL-Z background things and unbackground them.
function fg-bg() {
  if [[ $#BUFFER -eq 0 ]]; then
    fg
  else
    zle push-input
  fi
}
zle -N fg-bg
bindkey '^Z' fg-bg

# CTRL-Q quits the terminal
function quit() {
  exit
}
zle -N quit
bindkey '^Q' quit

# History search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Home End and Delete
bindkey '^[OH' beginning-of-line
bindkey '^[OF' end-of-line
bindkey '^[[3~' delete-char

autoload -Uz compinit; compinit
