- defaults:
    link:
      create: true
      relink: true

- clean:
    ~/bin/:
      recursive: true

- link:
    # Scripts
    ~/bin/wm-scripts/:
      glob: true
      path: config/wm-scripts/*

- create:
    - ~/bin
    - ~/bin/wm-scripts
