- defaults:
    link:
      create: true
      relink: true

# TODO: Check if this deletes other shared config
- clean:
    ~/:
      force: true
    ~/.config:
      recursive: true

- link:
    # I3
    ~/.config/i3/config: config/i3config.conf
