- defaults:
    link:
      create: true
      relink: true

- clean:
    ~/:
      force: true
    ~/.config:
      recursive: true

- link:
    ~/.config/bat/:
      glob: true
      path: config/bat/*
