#!/usr/bin/env python3

import os
import sys

import yaml


def removeConfig(config_file):
    """Removes all symlinks for a given configFile """
    stream = open(config_file, "r")
    conf = yaml.load(stream, Loader=yaml.FullLoader)
    for section in conf:
        if "link" in section:
            for target in section["link"]:
                realpath = os.path.expanduser(target)
                if os.path.islink(realpath):
                    print("Removing ", realpath)
                    os.unlink(realpath)


config_to_remove = None
if len(sys.argv) > 1:
    config_to_remove = sys.argv[1]

if config_to_remove:
    removeConfig(config_to_remove)
