#!/usr/bin/env python3

import getopt
import os
import sys

import yaml


def usage():
    print("Usage: uninstall [-sh] <config> ")


def removeConfig(config_file, silent):
    """Removes all symlinks for a given configFile """
    stream = open(config_file, "r")
    conf = yaml.load(stream, Loader=yaml.FullLoader)
    for section in conf:
        if "link" in section:
            for target in section["link"]:
                realpath = os.path.expanduser(target)
                if os.path.islink(realpath):
                    if not silent:
                        print("Removing ", realpath)
                    os.unlink(realpath)


def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "hs", ["silent", "help"])
    except getopt.GetoptError as err:
        # print help information and exit:
        print(err)  # will print something like "option -a not recognized"
        usage()
        sys.exit(2)
    silent = False
    for o, _ in opts:
        if o in ["-s", "--silent"]:
            silent = True
        elif o in ("-h", "--help"):
            usage()
            sys.exit()
        else:
            assert False, "unhandled option"
    for config in args:
        removeConfig(config, silent)


if __name__ == "__main__":
    main()
