#!/bin/sh
# This script is called on startup to remap keys.

# Map the caps lock key to super...
# setxkbmap -option caps:super
# # But when it is pressed only once, treat it as escape.
# killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape'

# Map the caps lock key to ctrl...
setxkbmap -option ctrl:nocaps
# But when it is pressed only once, treat it as escape.
killall xcape 2>/dev/null ;xcape -e 'Control_L=Escape'

xset r rate 280 35 # Increase key speed via a rate change
